spring.datasource.url=jdbc:postgresql://localhost:5432/doupark
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.springframework.security=DEBUG

spring.sql.init.mode=never

jwt.secret=doupark-super-secret-key-nazlican-2025-very-long-string
jwt.expiration=86400000
jwt.refresh-expiration=604800000